version: '3.8'

services:
  web:
    build:
      context: .
      network: host
    ports:
      - "8106:8000"
    volumes:
      - ./temp:/app/temp
      - ./.env:/app/.env
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s 