version: '3.8'

services:
  web:
    build:
      context: .
      network: host
    ports:
      - "8106:8000"
    volumes:
      - ./temp:/app/temp
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 4G  # 限制内存使用
        reservations:
          memory: 2G  # 预留内存 
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s 